`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 24.04.2026 23:33:26
// Design Name: 
// Module Name: router_top_tb
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////



module router_top_tb();
	reg clock,resetn,read_enb_0,read_enb_1,read_enb_2,pkt_valid;
	reg [7:0]data_in;
	wire [7:0]data_out_0,data_out_1,data_out_2;
	wire  valid_out_0,valid_out_1,valid_out_2,error,busy;
	router_top DUT(clock,resetn,read_enb_0,read_enb_1,read_enb_2,pkt_valid,data_in,
	data_out_0,data_out_1,data_out_2,valid_out_0,valid_out_1,valid_out_2,error,busy);
	
	integer i;
	// clock generation
	initial
	begin
		clock=1'b0;
		forever #5 clock=~clock;
	end
	//reset task
	task reset();
		begin
			@(negedge clock)
			resetn=1'b0;
			@(negedge clock)
			resetn=1'b1;
		end
	endtask
	//task fot payload len = 14
	task pkt_gen_14_1;
		reg[7:0]payload_data,parity,header;
		reg[5:0]payload_len;
		reg[1:0]addr;
		begin
			@(negedge clock)
			wait(~busy)
			@(negedge clock)
			payload_len=6'd14;
			addr=2'b01;//valid packet
			header={payload_len,addr};
			pkt_valid=1'b1;
			data_in=header;
			parity=0^header;
			@(negedge clock)
			wait(~busy)
			for(i=0;i<payload_len;i=i+1)
			begin
			@(negedge clock)
			wait(~busy)
			payload_data={$random}%256;
			data_in=payload_data;
			parity=parity^payload_data;
			end
			@(negedge clock)
			wait(~busy)
			pkt_valid=1'b0;
			data_in=parity;
		end
	endtask       
    	//task for payload len =16	
	task pkt_gen_16_1;
                reg[7:0]payload_data,parity,header;
                reg[5:0]payload_len;
                reg[1:0]addr;
                begin
                        @(negedge clock)
                        wait(~busy)
                        @(negedge clock)
                        payload_len=6'd16;
                        addr=2'b01;//valid packet
                        header={payload_len,addr};
                        parity=1'b0;
                        data_in=header;
                        parity=parity^header;
								pkt_valid=1'b1;
                        @(negedge clock)
                        wait(~busy)
                        for(i=0;i<payload_len;i=i+1)
                        begin
                        @(negedge clock)
                        wait(~busy)
                        payload_data={$random}%256;
                        data_in=payload_data;
                        parity=parity^payload_data;
                        end
                        @(negedge clock)
                        wait(~busy)
                        pkt_valid=1'b0;
                        data_in=parity;
                end
        endtask      
	//task for payload len < 14       
	task pkt_gen_14_2;
                reg[7:0]payload_data,parity,header;
                reg[5:0]payload_len;
                reg[1:0]addr;
                begin
                        @(negedge clock)
                        wait(~busy)
                        @(negedge clock)
                        payload_len=6'd12;
                        addr=2'b10;//valid packet
                        header={payload_len,addr};
                        parity=1'b0;
                        data_in=header;
                        parity=parity^header;
								pkt_valid=1'b1;
                        @(negedge clock)
                        wait(~busy)
                        for(i=0;i<payload_len;i=i+1)
                        begin
                        @(negedge clock)
                        wait(~busy)
                        payload_data={$random}%256;
                        data_in=payload_data;
                        parity=parity^payload_data;
                        end
                        @(negedge clock)
                        wait(~busy)
                        pkt_valid=1'b0;
                        data_in=parity;
                end
        endtask
	//task for payload len =17
	event e1;
	task pkt_gen_17;
		reg[7:0]payload_data,parity,header;
                reg[5:0]payload_len;
                reg[1:0]addr;
                begin
                       @(negedge clock)
                        wait(~busy)
                        @(negedge clock)
                        payload_len=6'd18;
			addr=2'b01;
			header={payload_len,addr};
			parity=0;
			data_in=header;
			pkt_valid=1;
			parity=parity^header;
			@(negedge clock)
			wait(~busy)
			for(i=0;i<payload_len;i=i+1)
			begin
				@(negedge clock)
			//	wait(~busy)
				payload_data={$random}%256;
				data_in=payload_data;
				parity=parity^header;
				
			end
			->e1;
			@(negedge clock)
			wait(~busy)
			pkt_valid=0;
			data_in=parity;
		end
	endtask       
	//task for random  payload len
event e2;	
	task pkt_gen_rand();
	
                reg[7:0]payload_data,parity,header;
                reg[5:0]payload_len;
                reg[1:0]addr;
					
	begin
                
                        @(negedge clock)
                        wait(~busy)
                        @(negedge clock)
                        payload_len={$random}%63+1;
                        addr=2'b01;
                        header={payload_len,addr};
                        parity=0;
                        data_in=header;
                        pkt_valid=1;
                        parity=parity^header;
                        @(negedge clock)
                        wait(~busy)
                        for(i=0;i<payload_len;i=i+1)
                        begin
                                @(negedge clock)
                                wait(~busy)
                                payload_data={$random}%256;
                                data_in=payload_data;
                                parity=parity^data_in;
										  data_in=parity;
                        end
                        ->e2;
                        @(negedge clock)
                        wait(~busy)
								pkt_valid=0;
               
			end
        endtask

	// read for pkt len = 17
	/*initial 
	begin
		@(e1)
		@(negedge clock)
		read_enb_2=1;
		@(negedge clock)
		wait(valid_out_2)
		@(negedge clock)
		read_enb_2=0; 
	end
*/


      // read for pkt len=random
      /*initial
      begin
	      @(e2)
	      @(negedge clock)
	      read_enb_2=1;
	      @(negedge clock)
	      wait(valid_out_2)
	      @(negedge clock)
	      read_enb_2=0;
      end*/

      // read pkt len=16
   /*initial
     begin
	    
              @(negedge clock)
              read_enb_2=1;
              @(negedge clock)
              wait(~valid_out_2)
              @(negedge clock)
              read_enb_2=0;
   end*/

   // read pkt len=14
   /*initial
   begin
	   
	   @(negedge clock)
	   read_enb_0=1;
	   @(negedge clock)
	   wait(~valid_out_0)
	   @(negedge clock)
	   read_enb_0=0;
   end*/

   // read pkt len<14
   /*initial
   begin
	   @(e1)
	   @(negedge clock)
	   read_enb_1=1;
	   @(negedge clock)
	   wait(~valid_out_1)
	   @(negedge clock)
	   read_enb_1=0;
   end
*/	
  /*initial
	begin
		reset();
	pkt_gen_17;
    
	end
    initial
	begin
	   @(e1)
	  
	   @(negedge clock)
	   read_enb_1=1;
		#100;
	   @(negedge clock)
	   wait(~valid_out_1)
	   @(negedge clock)
	   read_enb_1=0;
		
	#1000;
	end*/ 
	
	initial
	begin
	  
	  reset();
	  pkt_gen_14_1;
	   @(negedge clock)
	   read_enb_1=1;
	   @(negedge clock)
	   wait(~valid_out_1)
	   @(negedge clock)
	   read_enb_1=0;
	#1000;
	end 
	
	/*initial
	begin
		reset();
	pkt_gen_14_1;
	#100;
	end*/
 
	  /*
	   @(negedge clock)
	   read_enb_1=1;
	   @(negedge clock)
		#100;
	   wait(~valid_out_1)
	   @(negedge clock)
	   read_enb_1=0;
	#1000;
	end */
/*	pkt_gen_14_2;
	#100;
	pkt_gen_17;
	#100;
	pkt_gen_rand();*/
   endmodule


